Feature/lidar features bundle adjustment
ethz-asl/maplab pull request #265
Opened 2020-07-21 14:53 UTC by mariusbruehlmeier

**TODO:** ADD YOUR DESCRIPTION HERE

---

Before opening this pull request, please consider the following **checklist**:

 - For bug fixes:
   - Describe the bug or add a link to the maplab issue.
   - Ideally include instructions on how to reproduce it.
   - Describe your solution.
 - For new features:
   - Describe the new functionality and provide instructions on how to use it.
   - Add results (plots, pictures, videos).
   - Make sure this feature can be used on the existing maplab dataset, otherwise provide an example dataset.
   - Add a unit/integration/end-to-end test for this new feature.

WIP

**Open Questions:**

- _optimization-terms-addition.cc l.450_ During my thesis the camera type here was a LiDAR camera. This changed now to a pinhole camera. I guess this means the there are synchronized frames, with LiDAR and camera constraints. Currently, if a frame has LiDAR data, it will skip the camera data for the optimization.

2020-08-12 15:05 UTC, mariusbruehlmeier commented
test this please

2020-09-26 14:46 UTC, floriantschopp commented on console-plugins/landmark-manipulation-plugin/src/landmark-manipulation-plugin.cc
> +      "Evaluates and sets the landmark quality of all landmarks.",
```suggestion
      "Evaluates and sets the landmark quality of all lidar landmarks.",
```

2021-02-02 13:06 UTC, hexdforward commented
Hi, thanks for you pr to involve lidar features for higher precision and roubustness, have 2 question here:
1. The two dataset you mention above above seems not available, could you make it public？
2. Could you give a usage example for feature/lidar_features_compelete_pipeline and feature/lidar_features_bundle_adjustment? 
Thanks!
@mariusbruehlmeier

2021-02-03 09:23 UTC, mariusbruehlmeier commented
Hi @hexdforward 

Thanks for your interest in this PR.

1. The dataset belongs to ASL. I no longer work there and don't have access to the bag anymore. Maybe @floriantschopp can help you with this.

2. The work of this PR is my master thesis about LiDAR mapping. For the PR, I divided it into two parts. 

"feature/lidar_features_bundle_adjustment" contains all the backend needed to expand maplab with LiDAR features, i.e. map optimization, new landmark types and some very simple loop closure. It assumes that you already have detected, described and tracked LiDAR features .

"feature/lidar_features_compelete_pipeline" is the complete code of my thesis. It includes my version of LiDAR feature detection, mapping and description by using a 2D image. It should with a bag and the calibration file. However, it is much less cleaned up than the branch that I want to merge in this PR.

Let me know if this was helpful and if you have any more questions.

2021-02-25 09:27 UTC, hexdforward commented
Hi @mariusbruehlmeier, thank your reply so much.
Still have few question:
1. If the above dataset is not available, could you specify the dataset requirement(required topic, calibration file... ) so that I can use other data(such as kitti dataset, self collected dataset) to run with your PR.
2. Since you mention that this PR is  your master thesis. So have you test your PR with more dataset, such as kitti.
3. Is your thesis is available on the internet ? If not, could you share more about your thesis work, such as your published paper which is related your thesis work.
Thanks again!

2021-03-14 07:31 UTC, mariusbruehlmeier commented
@hexdforward 

The whole work will be part of a publication at a later stage and therefore I, unfortunately, cannot share my work at this time. 

The pipeline should be running with a data set as described in the general ROVIO & Maplab tutorials. The exact configs that I used are in this branch: https://github.com/ethz-asl/maplab/tree/feature/lidar_features_compelete_pipeline

2021-04-15 10:30 UTC, LBern reviewed
wip

2021-04-15 10:30 UTC, LBern commented on algorithms/ceres-error-terms/include/ceres-error-terms/lidar-error-term-factory-inl.h
> +    dummies_to_set_constant->push_back(dummy_7d_landmark_base_pose.data());
`emplace_back`

2021-04-15 10:30 UTC, LBern commented on algorithms/loopclosure/loop-closure-handler/src/loop-closure-handler.cc
> +  if (ncamera->getCameraShared(0)->getType() == aslam::Camera::Type::kLidar3D) {
why cam 0?

2021-04-15 15:39 UTC, LBern commented on map-structure/vi-map/src/lidar-landmark-quality-metrics.cc
> +    const Eigen::Vector3d p_C_fi = map.getLandmark_p_C_fi(
This is not used.

2021-04-15 16:30 UTC, LBern requested changes
another part

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/vi-map.cc
> +        VLOG(1) << "setting normal: " << sensor_id;
Debug prints

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/vi-mission.cc
> +      << "There is no valid NCamera ID associated with mission "
should mention that this is for the additional ncamera

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/vi-map.cc
> +#include <limits>
include order broken

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/sensor-utils.cc
> +    selected_lidar_ncamera_sensor_id, "", "Points to the lidar ncamera hack ");
better description

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/sensor-manager.cc
> +  for (const auto& sensor_with_id : sensors_) {
replace `auto`

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/lidar-landmark-quality-metrics.cc
> +    : max_distance_to_closest_observer_lidar(
`_` ending for members is missing

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/lidar-landmark-quality-metrics.cc
> +bool isLidarLandmarkWellConstrained(
can this function be `const`? some of the parameters definitely can be

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/lidar-landmark-quality-metrics.cc
> +  if (position_uncertainty / min_distance_to_lidar >
why `/ min_distance_to_lidar`?

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/lidar-landmark-quality-metrics.cc
> +  if (quality != vi_map::Landmark::Quality::kUnknown) {
this can be an `else`

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/lidar-landmark-quality-metrics.cc
> +  double distance_to_closest_observer = std::numeric_limits<double>::max();
`const double`

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/landmark-quality-metrics.cc
> +    vi_map_landmark_quality_min_observation_angle_deg, 0.0,
these should be reverted

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/landmark-quality-metrics.cc
> +    distance_to_closest_observer =
why the change?

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/check-map-consistency.cc
> +#include <vi-map/check-map-consistency.h>
include groups

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/check-map-consistency.cc
> +        VLOG(0) << "frame.hasKeypointMeasurements(): "
debug output

2021-04-15 16:30 UTC, LBern commented on map-structure/vi-map/src/check-map-consistency.cc
> +            VLOG(0) << "frame.hasKeypointMeasurements(): "
debug output

2021-04-15 16:30 UTC, LBern commented on console-plugins/landmark-manipulation-plugin/src/landmark-manipulation-plugin.cc
> +      "Retriangulate all landmarks.", common::Processing::Sync);
description should clarify for lidar

2021-04-15 16:30 UTC, LBern commented on common/aslam-serialization/src/visual-frame-serialization.cc
> +    VLOG(200) << "Frame " << frame.getId() << " has " << descriptors.cols()
debug output

2021-04-15 16:30 UTC, LBern commented on applications/rovioli/src/datasource-rostopic.cc
> +  int64_t diff = imu_measurement->timestamp - last_time_imu;
whats this

2021-04-15 16:30 UTC, LBern commented on applications/rovioli/src/datasource-rosbag.cc
> +       int64_t diff = imu_measurement->timestamp - last_time_imu;
hmmmmmmmmm

2021-04-15 16:30 UTC, LBern commented on applications/rovioli/include/rovioli/imu-camera-synchronizer-flow.h
> +          int64_t diff = imu->timestamp - this->last_imu_time;
is this needed?

2021-04-15 16:30 UTC, LBern commented on applications/rovioli/include/rovioli/feature-tracking-flow.h
> +    tracking_pipeline_new_.reset(
`new_` is not a explanatory name

2021-04-15 16:30 UTC, LBern commented on applications/rovioli/include/rovioli/datasource-rostopic.h
> +  int64_t last_time_imu = 0;
needed?

2021-04-15 16:30 UTC, LBern commented on applications/rovioli/include/rovioli/datasource-rosbag.h
> +  int64_t last_time_imu = 0;
needed?

2021-04-15 16:30 UTC, LBern commented on applications/maplab-node/src/lidar-tracking.cc
> +          *camera_system,
`CHECK_NOTNULL`

2021-04-15 16:30 UTC, LBern commented on applications/maplab-node/src/lidar-tracking.cc
> +        << "[MaplabNode-Synchronizer] Failed to process an image of camera "
this is not the `MaplabNode-Synchronizer`

2021-04-15 16:30 UTC, LBern commented on applications/maplab-node/include/maplab-node/synchronizer-flow.h
> +  int64_t last_imu_time = 0;
needed?

2021-04-15 16:30 UTC, LBern commented on applications/maplab-node/include/maplab-node/lidar-tracking.h
> +#include <Eigen/Core>
include order

2021-04-15 16:30 UTC, LBern commented on applications/maplab-node/include/maplab-node/lidar-feature-flow.h
> +#include <message-flow/message-flow.h>
include order

2021-04-15 16:30 UTC, LBern commented on applications/maplab-node/include/maplab-node/datasource-rosbag.h
> +  int64_t last_imu_time = 0;
needed?

2021-04-15 16:30 UTC, LBern commented on applications/maplab-node/include/maplab-node/lidar-feature-flow.h
> +          cv::Mat cropped = feature_image;  //(cv::Rect(128, 0, 512, 64));
debug windows

2021-04-15 16:30 UTC, LBern commented on applications/maplab-node/CMakeLists.txt
> +add_compile_options(-w -std=c++14 -fPIC)
should not be needed

2021-04-15 16:30 UTC, LBern commented on algorithms/vi-map-helpers/src/vi-map-manipulation.cc
> +  VLOG(0) << "Map size: " << map_.numLandmarks();
debug output

2021-04-15 16:30 UTC, LBern commented on algorithms/vi-map-helpers/src/vi-map-manipulation.cc
> +      VLOG(0) << "Frame has no tracking information. Skipping frame...";
change verbosity

2021-04-15 18:51 UTC, LBern requested changes
another quick pass

2021-04-15 18:51 UTC, LBern commented on algorithms/map-optimization/include/map-optimization/outlier-rejection-solver.h
> +  double max_lidar_error = 0.05;
could be a bit more descriptive

2021-04-15 18:51 UTC, LBern commented on algorithms/lidar-features/lidar-feature-extraction/src/loam-features.cc
> +void LidarFeatureExtraction::projectPointCloud() {
haven't seen this one in a while. wth is it doing here

2021-04-15 18:51 UTC, LBern commented on algorithms/lidar-features/lidar-feature-extraction/src/image-projection.cc
> +  // cv::imshow("Gradient Range", range_gradient);
we should remove the commented lines

2021-04-15 18:51 UTC, LBern commented on algorithms/lidar-features/lidar-feature-extraction/src/image-projection.cc
> +    // cv::namedWindow("Intensity eq non_filt", cv::WINDOW_NORMAL);
whats the point of the flag then?

2021-04-15 18:51 UTC, LBern commented on algorithms/lidar-features/lidar-feature-extraction/include/lidar-feature-extraction/loam-features.h
> +class LidarFeatureExtraction {
is this used?

2021-04-15 18:51 UTC, LBern commented on algorithms/le-feature-tracking/feature-tracking-pipelines/include/feature-tracking-pipelines/visualizations.h
> +#ifndef FEATURE_TRACKING_PIPELINES_VISUALIZATIONS_H_
delete

2021-04-15 18:51 UTC, LBern commented on algorithms/le-feature-tracking/feature-tracking-pipelines/include/feature-tracking-pipelines/feature-pipeline-lk-tracking-laser.h
> +#include <Eigen/Core>
include groups/order

2021-04-15 18:51 UTC, LBern commented on algorithms/le-feature-tracking/feature-tracking-pipelines/CMakeLists.txt
> +#catkin_add_gtest(test_feature_extractor
unused gtests

2021-04-15 18:51 UTC, LBern commented on algorithms/landmark-triangulation/src/landmark-triangulation.cc
> +  vi_map::MissionIdList mission_ids;
`CHECK_NOTNULL(map)`

2021-04-15 18:51 UTC, LBern commented on algorithms/landmark-triangulation/src/landmark-triangulation.cc
> +  FrameToPoseMap interpolated_frame_poses;
`CHECK_NOTNULL(map)`

2021-04-19 13:56 UTC, LBern commented on algorithms/ceres-error-terms/include/ceres-error-terms/lidar-error-term.h
> +    kIdxCameraIntrinsics,
can we remove the intrinsics? why do we need the imu poses?

2021-04-19 13:56 UTC, LBern commented on algorithms/ceres-error-terms/include/ceres-error-terms/lidar-error-term.h
> +      DistortionJacobian;
Not needed here.

2021-04-19 13:58 UTC, LBern commented on algorithms/landmark-triangulation/src/landmark-triangulation.cc
> +#include <functional>
include order

2021-04-20 05:04 UTC, LBern commented on algorithms/ceres-error-terms/test/test_lidar_term_test.cc
> +  // problem_.SetParameterBlockConstant(camera1_pose.data());
should this be uncommented?

2021-04-20 05:10 UTC, LBern commented on algorithms/le-feature-tracking/feature-tracking-pipelines/include/feature-tracking-pipelines/feature-pipeline-matching-based.h
> +#define FEATURE_TRACKING_PIPELINES_FEATURE_PIPELINE_MATCHING_BASED_H_
remove?

2021-04-20 11:42 UTC, LBern commented on algorithms/ceres-error-terms/include/ceres-error-terms/lidar-error-term.h
> +          CameraType::parameterCount(), DistortionType::parameterCount()>,
we don't have a distortion block

2021-11-04 08:49 UTC, LBern commented
Closing this now. Moved to a separate package.

2021-11-04 08:49 UTC, closed without merging