MaplabNode Idle Mode
ethz-asl/maplab pull request #328
Opened 2021-08-10 10:36 UTC by LBern

## General
This PR adds the possibility to set the `maplab_node` to an idle mode in which no new maps are built. Only the current submap data (and any other remaining) will be sent over `transfolder` to the `maplab_server_ndoe`. 

## Changelog
 * Added service call to set idle mode.
 * Added flag to control the automatic shutdown of the `maplab_node`.

## Usage
The advertised service is called: `go_idle`. Example with calling it from the console: 
> rosservice call /anymal_5/go_idle

2021-08-10 10:36 UTC, LBern commented
FYI @marco-tranzatto

2021-08-13 12:15 UTC, patripfr submitted a review, later dismissed
lgtm, thanks!

2021-08-13 12:31 UTC, patripfr commented on applications/maplab-node/src/synchronizer.cc
> +    enable_synchronizer_automatic_shudown, true,
```suggestion
    enable_synchronizer_automatic_shutdown, true,
```

2021-08-13 12:31 UTC, patripfr commented on applications/maplab-node/src/synchronizer.cc
> +          if (FLAGS_enable_synchronizer_automatic_shudown) {
```suggestion
          if (FLAGS_enable_synchronizer_automatic_shutdown) {
```

2021-08-13 12:32 UTC, patripfr requested changes
fix typo then lgtm

2021-08-13 13:09 UTC, patripfr approved these changes
lgtm

2021-08-16 09:47 UTC, merged